Document: acme-sh
Title: Debian acme-sh Manual
Author: <insert document author here>
Abstract: This manual describes what acme-sh is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/acme-sh/acme-sh.sgml.gz

Format: postscript
Files: /usr/share/doc/acme-sh/acme-sh.ps.gz

Format: text
Files: /usr/share/doc/acme-sh/acme-sh.text.gz

Format: HTML
Index: /usr/share/doc/acme-sh/html/index.html
Files: /usr/share/doc/acme-sh/html/*.html
